language: ruby
rvm:
 - 1.9.3

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/site.yml.tmpl config/site.yml"
  - "cp config/database.yml.tmpl config/database.yml"

script: "bundle exec rake db:setup"

after_script: "mysqldump --no-data tracks_test"

bundler_args: --without development
notifications:
  email: false

